'use strict';
import { Op, QueryInterface } from 'sequelize';

module.exports = {
  async up (queryInterface: QueryInterface, Sequelize: any) {
    return await queryInterface.bulkInsert('country_cat', [
      {
        id: 1,
        en: 'Andorra',
        es: 'Andorra',
        iso2: 'AD',
        iso3: 'AND',
        currencyCode: 'EUR',
        phoneCode: '+376',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 2,
        en: 'United Arab Emirates',
        es: 'Emiratos Árabes Unidos',
        iso2: 'AE',
        iso3: 'ARE',
        currencyCode: 'AED',
        phoneCode: '+971',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 3,
        en: 'Afghanistan',
        es: 'Afganistán',
        iso2: 'AF',
        iso3: 'AFG',
        currencyCode: 'AFN',
        phoneCode: '+93',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 4,
        en: 'Antigua and Barbuda',
        es: 'Antigua y Barbuda',
        iso2: 'AG',
        iso3: 'ATG',
        currencyCode: 'XCD',
        phoneCode: '+1-268',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 5,
        en: 'Anguilla',
        es: 'Anguila',
        iso2: 'AI',
        iso3: 'AIA',
        currencyCode: 'N/A',
        phoneCode: '+1-264',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 6,
        en: 'Albania',
        es: 'Albania',
        iso2: 'AL',
        iso3: 'ALB',
        currencyCode: 'ALL',
        phoneCode: '+355',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 7,
        en: 'Armenia',
        es: 'Armenia',
        iso2: 'AM',
        iso3: 'ARM',
        currencyCode: 'AMD',
        phoneCode: '+374',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 8,
        en: 'Angola',
        es: 'Angola',
        iso2: 'AO',
        iso3: 'AGO',
        currencyCode: 'AON',
        phoneCode: '+244',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 9,
        en: 'Antarctica',
        es: 'Antártida',
        iso2: 'AQ',
        iso3: 'ATA',
        currencyCode: 'N/A',
        phoneCode: '+672',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 10,
        en: 'Argentina',
        es: 'Argentina',
        iso2: 'AR',
        iso3: 'ARG',
        currencyCode: 'ARS',
        phoneCode: '+54',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 11,
        en: 'American Samoa',
        es: 'Samoa Americana',
        iso2: 'AS',
        iso3: 'ASM',
        currencyCode: 'N/A',
        phoneCode: '+1-684',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 12,
        en: 'Austria',
        es: 'Austria',
        iso2: 'AT',
        iso3: 'AUT',
        currencyCode: 'EUR',
        phoneCode: '+43',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 13,
        en: 'Australia',
        es: 'Australia',
        iso2: 'AU',
        iso3: 'AUS',
        currencyCode: 'AUD',
        phoneCode: '+61',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 14,
        en: 'Aruba',
        es: 'Aruba',
        iso2: 'AW',
        iso3: 'ABW',
        currencyCode: 'N/A',
        phoneCode: '+297',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 15,
        en: 'Alland Islands',
        es: 'Islas Aland',
        iso2: 'AX',
        iso3: 'ALA',
        currencyCode: 'N/A',
        phoneCode: '+358',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 16,
        en: 'Azerbaijan',
        es: 'Azerbaiyán',
        iso2: 'AZ',
        iso3: 'AZE',
        currencyCode: 'AZN',
        phoneCode: '+994',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 17,
        en: 'Bosnia and Herzegovina',
        es: 'Bosnia y Herzegovina',
        iso2: 'BA',
        iso3: 'BIH',
        currencyCode: 'BAM',
        phoneCode: '+387',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 18,
        en: 'Barbados',
        es: 'Barbados',
        iso2: 'BB',
        iso3: 'BRB',
        currencyCode: 'BBD',
        phoneCode: '+1-246',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 19,
        en: 'Bangladesh',
        es: 'Bangladesh',
        iso2: 'BD',
        iso3: 'BGD',
        currencyCode: 'BDT',
        phoneCode: '+880',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 20,
        en: 'Belgium',
        es: 'Bélgica',
        iso2: 'BE',
        iso3: 'BEL',
        currencyCode: 'EUR',
        phoneCode: '+32',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 21,
        en: 'Burkina Faso',
        es: 'Burkina Faso',
        iso2: 'BF',
        iso3: 'BFA',
        currencyCode: 'XOF',
        phoneCode: '+226',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 22,
        en: 'Bulgaria',
        es: 'Bulgaria',
        iso2: 'BG',
        iso3: 'BGR',
        currencyCode: 'BGL',
        phoneCode: '+359',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 23,
        en: 'Bahrain',
        es: 'Bahrein',
        iso2: 'BH',
        iso3: 'BHR',
        currencyCode: 'BHD',
        phoneCode: '+973',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 24,
        en: 'Burundi',
        es: 'Burundi',
        iso2: 'BI',
        iso3: 'BDI',
        currencyCode: 'BIF',
        phoneCode: '+257',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 25,
        en: 'Benin',
        es: 'Benin',
        iso2: 'BJ',
        iso3: 'BEN',
        currencyCode: 'XOF',
        phoneCode: '+229',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 26,
        en: 'Saint Barthelemy',
        es: 'San Bartolomé',
        iso2: 'BL',
        iso3: 'BLM',
        currencyCode: 'N/A',
        phoneCode: '+590',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 27,
        en: 'Bermuda',
        es: 'Bermudas',
        iso2: 'BM',
        iso3: 'BMU',
        currencyCode: 'BMD',
        phoneCode: '+1-441',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 28,
        en: 'Brunei Darussalam',
        es: 'Brunei Darussalam',
        iso2: 'BN',
        iso3: 'BRN',
        currencyCode: 'BND',
        phoneCode: '+673',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 29,
        en: 'Bolivia',
        es: 'Bolivia',
        iso2: 'BO',
        iso3: 'BOL',
        currencyCode: 'BOB',
        phoneCode: '+591',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 30,
        en: 'Brazil',
        es: 'Brasil',
        iso2: 'BR',
        iso3: 'BRA',
        currencyCode: 'BRL',
        phoneCode: '+55',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 31,
        en: 'Bahamas',
        es: 'Bahamas',
        iso2: 'BS',
        iso3: 'BHS',
        currencyCode: 'BSD',
        phoneCode: '+1-242',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 32,
        en: 'Bhutan',
        es: 'Bhután',
        iso2: 'BT',
        iso3: 'BTN',
        currencyCode: 'BTN',
        phoneCode: '+975',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 33,
        en: 'Bouvet Island',
        es: 'Isla Bouvet',
        iso2: 'BV',
        iso3: 'BVT',
        currencyCode: 'N/A',
        phoneCode: '+47',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 34,
        en: 'Botswana',
        es: 'Botswana',
        iso2: 'BW',
        iso3: 'BWA',
        currencyCode: 'BWP',
        phoneCode: '+267',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 35,
        en: 'Belarus',
        es: 'Belarús',
        iso2: 'BY',
        iso3: 'BLR',
        currencyCode: 'BYN',
        phoneCode: '+375',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 36,
        en: 'Belize',
        es: 'Belice',
        iso2: 'BZ',
        iso3: 'BLZ',
        currencyCode: 'BZD',
        phoneCode: '+501',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 37,
        en: 'Canada',
        es: 'Canadá',
        iso2: 'CA',
        iso3: 'CAN',
        currencyCode: 'CAD',
        phoneCode: '+1',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 38,
        en: 'Cocos Islands (Keeling)',
        es: 'Islas Cocos (Keeling)',
        iso2: 'CC',
        iso3: 'CCK',
        currencyCode: 'N/A',
        phoneCode: '+61',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 39,
        en: 'Democratic Republic of the Congo',
        es: 'República Democrática del Congo',
        iso2: 'CD',
        iso3: 'COD',
        currencyCode: 'CDF',
        phoneCode: '+243',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 40,
        en: 'Central African Republic',
        es: 'República Centroafricana',
        iso2: 'CF',
        iso3: 'CAF',
        currencyCode: 'XAF',
        phoneCode: '+236',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 41,
        en: 'Republic of the Congo',
        es: 'República del Congo',
        iso2: 'CG',
        iso3: 'COG',
        currencyCode: 'XAF',
        phoneCode: '+242',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 42,
        en: 'Switzerland',
        es: 'Suiza',
        iso2: 'CH',
        iso3: 'CHE',
        currencyCode: 'CHF',
        phoneCode: '+41',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 43,
        en: 'Cote d\'Ivoire',
        es: 'Côte d\'Ivoire',
        iso2: 'CI',
        iso3: 'CIV',
        currencyCode: 'XAF',
        phoneCode: '+225',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 44,
        en: 'Cook Islands',
        es: 'Islas Cooks',
        iso2: 'CK',
        iso3: 'COK',
        currencyCode: 'NZD',
        phoneCode: '+682',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 45,
        en: 'Chile',
        es: 'Chile',
        iso2: 'CL',
        iso3: 'CHL',
        currencyCode: 'CLP',
        phoneCode: '+56',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 46,
        en: 'Cameroon',
        es: 'Camerún',
        iso2: 'CM',
        iso3: 'CMR',
        currencyCode: 'XAF',
        phoneCode: '+237',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 47,
        en: 'China',
        es: 'China',
        iso2: 'CN',
        iso3: 'CHN',
        currencyCode: 'CNY',
        phoneCode: '+86',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 48,
        en: 'Colombia',
        es: 'Colombia',
        iso2: 'CO',
        iso3: 'COL',
        currencyCode: 'COP',
        phoneCode: '+57',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 49,
        en: 'Costa Rica',
        es: 'Costa Rica',
        iso2: 'CR',
        iso3: 'CRI',
        currencyCode: 'CRC',
        phoneCode: '+506',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 50,
        en: 'Cuba',
        es: 'Cuba',
        iso2: 'CU',
        iso3: 'CUB',
        currencyCode: 'CUP',
        phoneCode: '+53',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 51,
        en: 'Cape Verde',
        es: 'Cabo Verde',
        iso2: 'CV',
        iso3: 'CPV',
        currencyCode: 'CVE',
        phoneCode: '+238',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 52,
        en: 'Curacao',
        es: 'Curazao',
        iso2: 'CW',
        iso3: 'CUW',
        currencyCode: 'N/A',
        phoneCode: '+599',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 53,
        en: 'Christmas Island',
        es: 'Isla de Navidad',
        iso2: 'CX',
        iso3: 'CXR',
        currencyCode: 'N/A',
        phoneCode: '+61',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 54,
        en: 'Cyprus',
        es: 'Chipre',
        iso2: 'CY',
        iso3: 'CYP',
        currencyCode: 'EUR',
        phoneCode: '+357',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 55,
        en: 'Czech Republic',
        es: 'República Checa',
        iso2: 'CZ',
        iso3: 'CZE',
        currencyCode: 'EUR',
        phoneCode: '+420',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 56,
        en: 'Germany',
        es: 'Alemania',
        iso2: 'DE',
        iso3: 'DEU',
        currencyCode: 'EUR',
        phoneCode: '+49',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 57,
        en: 'Djibouti',
        es: 'Djibouti',
        iso2: 'DJ',
        iso3: 'DJI',
        currencyCode: 'DJF',
        phoneCode: '+253',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 58,
        en: 'Denmark',
        es: 'Dinamarca',
        iso2: 'DK',
        iso3: 'DNK',
        currencyCode: 'DKK',
        phoneCode: '+45',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 59,
        en: 'Dominica',
        es: 'Dominica',
        iso2: 'DM',
        iso3: 'DMA',
        currencyCode: 'XCD',
        phoneCode: '+1-767',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 60,
        en: 'Dominican Republic',
        es: 'República Dominicana',
        iso2: 'DO',
        iso3: 'DOM',
        currencyCode: 'DOP',
        phoneCode: '+1-809',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 61,
        en: 'Algeria',
        es: 'Argelia',
        iso2: 'DZ',
        iso3: 'DZA',
        currencyCode: 'DZD',
        phoneCode: '+213',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 62,
        en: 'Ecuador',
        es: 'Ecuador',
        iso2: 'EC',
        iso3: 'ECU',
        currencyCode: 'USD',
        phoneCode: '+593',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 63,
        en: 'Estonia',
        es: 'Estonia',
        iso2: 'EE',
        iso3: 'EST',
        currencyCode: 'EUR',
        phoneCode: '+372',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 64,
        en: 'Egypt',
        es: 'Egipto',
        iso2: 'EG',
        iso3: 'EGY',
        currencyCode: 'EGP',
        phoneCode: '+20',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 65,
        en: 'Western Sahara',
        es: 'Sahara Occidental',
        iso2: 'EH',
        iso3: 'ESH',
        currencyCode: 'N/A',
        phoneCode: '+212',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 66,
        en: 'Eritrea',
        es: 'Eritrea',
        iso2: 'ER',
        iso3: 'ERI',
        currencyCode: 'ERN',
        phoneCode: '+291',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 67,
        en: 'Spain',
        es: 'España',
        iso2: 'ES',
        iso3: 'ESP',
        currencyCode: 'EUR',
        phoneCode: '+34',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 68,
        en: 'Ethiopia',
        es: 'Etiopía',
        iso2: 'ET',
        iso3: 'ETH',
        currencyCode: 'ETB',
        phoneCode: '+251',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 69,
        en: 'Finland',
        es: 'Finlandia',
        iso2: 'FI',
        iso3: 'FIN',
        currencyCode: 'EUR',
        phoneCode: '+358',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 70,
        en: 'Fiji',
        es: 'Fiji',
        iso2: 'FJ',
        iso3: 'FJI',
        currencyCode: 'FJD',
        phoneCode: '+679',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 71,
        en: 'Falkland Islands (Malvinas)',
        es: 'Islas Malvinas',
        iso2: 'FK',
        iso3: 'FLK',
        currencyCode: 'N/A',
        phoneCode: '+500',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 72,
        en: 'Federated States of Micronesia',
        es: 'Estados Federados de Micronesia',
        iso2: 'FM',
        iso3: 'FSM',
        currencyCode: 'USD',
        phoneCode: '+691',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 73,
        en: 'Faroe Islands',
        es: 'Islas Feroe',
        iso2: 'FO',
        iso3: 'FRO',
        currencyCode: 'N/A',
        phoneCode: '+298',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 74,
        en: 'France',
        es: 'Francia',
        iso2: 'FR',
        iso3: 'FRA',
        currencyCode: 'EUR',
        phoneCode: '+33',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 75,
        en: 'Gabon',
        es: 'Gabón',
        iso2: 'GA',
        iso3: 'GAB',
        currencyCode: 'XAF',
        phoneCode: '+241',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 76,
        en: 'United Kingdom',
        es: 'Reino Unido de Gran Bretaña e Irlanda del Norte',
        iso2: 'GB',
        iso3: 'GBR',
        currencyCode: 'GBP',
        phoneCode: '+44',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 77,
        en: 'Grenada',
        es: 'Granada',
        iso2: 'GD',
        iso3: 'GRD',
        currencyCode: 'XCD',
        phoneCode: '+1-473',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 78,
        en: 'Georgia',
        es: 'Georgia',
        iso2: 'GE',
        iso3: 'GEO',
        currencyCode: 'GEL',
        phoneCode: '+995',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 79,
        en: 'French Guiana',
        es: 'Guayana Francesa',
        iso2: 'GF',
        iso3: 'GUF',
        currencyCode: 'N/A',
        phoneCode: '+594',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 80,
        en: 'Guernsey',
        es: 'Guernsey',
        iso2: 'GG',
        iso3: 'GGY',
        currencyCode: 'N/A',
        phoneCode: '+44',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 81,
        en: 'Ghana',
        es: 'Ghana',
        iso2: 'GH',
        iso3: 'GHA',
        currencyCode: 'GHC',
        phoneCode: '+233',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 82,
        en: 'Gibraltar',
        es: 'Gibraltar',
        iso2: 'GI',
        iso3: 'GIB',
        currencyCode: 'N/A',
        phoneCode: '+350',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 83,
        en: 'Greenland',
        es: 'Groenlandia',
        iso2: 'GL',
        iso3: 'GRL',
        currencyCode: 'N/A',
        phoneCode: '+299',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 84,
        en: 'Gambia',
        es: 'Gambia',
        iso2: 'GM',
        iso3: 'GMB',
        currencyCode: 'GMD',
        phoneCode: '+220',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 85,
        en: 'Guinea',
        es: 'Guinea',
        iso2: 'GN',
        iso3: 'GIN',
        currencyCode: 'GNF',
        phoneCode: '+224',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 86,
        en: 'Guadeloupe',
        es: 'Guadalupe',
        iso2: 'GP',
        iso3: 'GLP',
        currencyCode: 'N/A',
        phoneCode: '+590',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 87,
        en: 'Equatorial Guinea',
        es: 'Guinea Ecuatorial',
        iso2: 'GQ',
        iso3: 'GNQ',
        currencyCode: 'XAF',
        phoneCode: '+240',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 88,
        en: 'Greece',
        es: 'Grecia',
        iso2: 'GR',
        iso3: 'GRC',
        currencyCode: 'EUR',
        phoneCode: '+30',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 89,
        en: 'South Georgia and the South Sandwich Islands',
        es: 'Islas Georgias del Sur y Sandwich del Sur',
        iso2: 'GS',
        iso3: 'SGS',
        currencyCode: 'N/A',
        phoneCode: '+500',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 90,
        en: 'Guatemala',
        es: 'Guatemala',
        iso2: 'GT',
        iso3: 'GTM',
        currencyCode: 'GTQ',
        phoneCode: '+502',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 91,
        en: 'Guam',
        es: 'Guam',
        iso2: 'GU',
        iso3: 'GUM',
        currencyCode: 'N/A',
        phoneCode: '+1-671',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 92,
        en: 'Guinea-Bissau',
        es: 'Guinea-Bissau',
        iso2: 'GW',
        iso3: 'GNB',
        currencyCode: 'XAF',
        phoneCode: '+245',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 93,
        en: 'Guyana',
        es: 'Guyana',
        iso2: 'GY',
        iso3: 'GUY',
        currencyCode: 'GYD',
        phoneCode: '+592',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 94,
        en: 'Hong Kong',
        es: 'Hong Kong',
        iso2: 'HK',
        iso3: 'HKG',
        currencyCode: 'N/A',
        phoneCode: '+852',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 95,
        en: 'Heard Island and McDonald Islands',
        es: 'Islas Heard y McDonald',
        iso2: 'HM',
        iso3: 'HMD',
        currencyCode: 'N/A',
        phoneCode: '+672',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 96,
        en: 'Honduras',
        es: 'Honduras',
        iso2: 'HN',
        iso3: 'HND',
        currencyCode: 'HNL',
        phoneCode: '+504',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 97,
        en: 'Croatia',
        es: 'Croacia',
        iso2: 'HR',
        iso3: 'HRV',
        currencyCode: 'HRK',
        phoneCode: '+385',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 98,
        en: 'Haiti',
        es: 'Haití',
        iso2: 'HT',
        iso3: 'HTI',
        currencyCode: 'HTG',
        phoneCode: '+509',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 99,
        en: 'Hungary',
        es: 'Hungría',
        iso2: 'HU',
        iso3: 'HUN',
        currencyCode: 'HUF',
        phoneCode: '+36',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 100,
        en: 'Indonesia',
        es: 'Indonesia',
        iso2: 'ID',
        iso3: 'IDN',
        currencyCode: 'IDR',
        phoneCode: '+62',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 101,
        en: 'Ireland',
        es: 'Irlanda',
        iso2: 'IE',
        iso3: 'IRL',
        currencyCode: 'EUR',
        phoneCode: '+353',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 102,
        en: 'Israel',
        es: 'Israel',
        iso2: 'IL',
        iso3: 'ISR',
        currencyCode: 'ILS',
        phoneCode: '+972',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 103,
        en: 'Isle of Man',
        es: 'Isla de Man',
        iso2: 'IM',
        iso3: 'IMN',
        currencyCode: 'N/A',
        phoneCode: '+44',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 104,
        en: 'India',
        es: 'India',
        iso2: 'IN',
        iso3: 'IND',
        currencyCode: 'INR',
        phoneCode: '+91',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 105,
        en: 'British Indian Ocean Territory',
        es: 'Territorio Británico del Océano Índico',
        iso2: 'IO',
        iso3: 'IOT',
        currencyCode: 'N/A',
        phoneCode: '+246',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 106,
        en: 'Iraq',
        es: 'Iraq',
        iso2: 'IQ',
        iso3: 'IRQ',
        currencyCode: 'IQD',
        phoneCode: '+964',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 107,
        en: 'Islamic Republic of Iran',
        es: 'República Islámica del Irán',
        iso2: 'IR',
        iso3: 'IRN',
        currencyCode: 'IRR',
        phoneCode: '+98',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 108,
        en: 'Iceland',
        es: 'Islandia',
        iso2: 'IS',
        iso3: 'ISL',
        currencyCode: 'ISK',
        phoneCode: '+354',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 109,
        en: 'Italy',
        es: 'Italia',
        iso2: 'IT',
        iso3: 'ITA',
        currencyCode: 'EUR',
        phoneCode: '+39',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 110,
        en: 'Jersey',
        es: 'Jersey',
        iso2: 'JE',
        iso3: 'JEY',
        currencyCode: 'N/A',
        phoneCode: '+44',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 111,
        en: 'Jamaica',
        es: 'Jamaica',
        iso2: 'JM',
        iso3: 'JAM',
        currencyCode: 'JMD',
        phoneCode: '+1-876',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 112,
        en: 'Jordan',
        es: 'Jordania',
        iso2: 'JO',
        iso3: 'JOR',
        currencyCode: 'JOD',
        phoneCode: '+962',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 113,
        en: 'Japan',
        es: 'Japón',
        iso2: 'JP',
        iso3: 'JPN',
        currencyCode: 'JPY',
        phoneCode: '+81',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 114,
        en: 'Kenya',
        es: 'Kenya',
        iso2: 'KE',
        iso3: 'KEN',
        currencyCode: 'KES',
        phoneCode: '+254',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 115,
        en: 'Kyrgyzstan',
        es: 'Kirguistán',
        iso2: 'KG',
        iso3: 'KGZ',
        currencyCode: 'KGS',
        phoneCode: '+996',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 116,
        en: 'Cambodia',
        es: 'Camboya',
        iso2: 'KH',
        iso3: 'KHM',
        currencyCode: 'KHR',
        phoneCode: '+855',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 117,
        en: 'Kiribati',
        es: 'Kiribati',
        iso2: 'KI',
        iso3: 'KIR',
        currencyCode: 'AUD',
        phoneCode: '+686',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 118,
        en: 'Comoros',
        es: 'Comoras',
        iso2: 'KM',
        iso3: 'COM',
        currencyCode: 'KMF',
        phoneCode: '+269',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 119,
        en: 'Saint Kitts and Nevis',
        es: 'Saint Kitts y Nevis',
        iso2: 'KN',
        iso3: 'KNA',
        currencyCode: 'XCD',
        phoneCode: '+1-869',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 120,
        en: 'Democratic People\'s Republic of Korea',
        es: 'República Popular Democrática de Corea',
        iso2: 'KP',
        iso3: 'PRK',
        currencyCode: 'KPW',
        phoneCode: '+850',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 121,
        en: 'Republic of Korea',
        es: 'República de Corea',
        iso2: 'KR',
        iso3: 'KOR',
        currencyCode: 'KRW',
        phoneCode: '+82',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 122,
        en: 'Kuwait',
        es: 'Kuwait',
        iso2: 'KW',
        iso3: 'KWT',
        currencyCode: 'KWD',
        phoneCode: '+965',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 123,
        en: 'Cayman Islands',
        es: 'Islas Caimán',
        iso2: 'KY',
        iso3: 'CYM',
        currencyCode: 'N/A',
        phoneCode: '+1-345',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 124,
        en: 'Kazakhstan',
        es: 'Kazajstán',
        iso2: 'KZ',
        iso3: 'KAZ',
        currencyCode: 'KZT',
        phoneCode: '+7',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 125,
        en: 'Lao People\'s Democratic Republic',
        es: 'República Democrática Popular Lao',
        iso2: 'LA',
        iso3: 'LAO',
        currencyCode: 'LAK',
        phoneCode: '+856',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 126,
        en: 'Lebanon',
        es: 'Líbano',
        iso2: 'LB',
        iso3: 'LBN',
        currencyCode: 'LBP',
        phoneCode: '+961',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 127,
        en: 'Saint Lucia',
        es: 'Santa Lucía',
        iso2: 'LC',
        iso3: 'LCA',
        currencyCode: 'XCD',
        phoneCode: '+1-758',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 128,
        en: 'Liechtenstein',
        es: 'Liechtenstein',
        iso2: 'LI',
        iso3: 'LIE',
        currencyCode: 'N/A',
        phoneCode: '+423',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 129,
        en: 'Sri Lanka',
        es: 'Sri Lanka',
        iso2: 'LK',
        iso3: 'LKA',
        currencyCode: 'LKR',
        phoneCode: '+94',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 130,
        en: 'Liberia',
        es: 'Liberia',
        iso2: 'LR',
        iso3: 'LBR',
        currencyCode: 'LRD',
        phoneCode: '+231',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 131,
        en: 'Lesotho',
        es: 'Lesotho',
        iso2: 'LS',
        iso3: 'LSO',
        currencyCode: 'LSL',
        phoneCode: '+266',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 132,
        en: 'Lithuania',
        es: 'Lituania',
        iso2: 'LT',
        iso3: 'LTU',
        currencyCode: 'EUR',
        phoneCode: '+370',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 133,
        en: 'Luxembourg',
        es: 'Luxemburgo',
        iso2: 'LU',
        iso3: 'LUX',
        currencyCode: 'EUR',
        phoneCode: '+352',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 134,
        en: 'Latvia',
        es: 'Letonia',
        iso2: 'LV',
        iso3: 'LVA',
        currencyCode: 'EUR',
        phoneCode: '+371',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 135,
        en: 'Libya',
        es: 'Libia',
        iso2: 'LY',
        iso3: 'LBY',
        currencyCode: 'LYD',
        phoneCode: '+218',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 136,
        en: 'Morocco',
        es: 'Marruecos',
        iso2: 'MA',
        iso3: 'MAR',
        currencyCode: 'MAD',
        phoneCode: '+212',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 137,
        en: 'Monaco',
        es: 'Mónaco',
        iso2: 'MC',
        iso3: 'MCO',
        currencyCode: 'EUR',
        phoneCode: '+377',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 138,
        en: 'Republic of Moldova',
        es: 'República de Moldova',
        iso2: 'MD',
        iso3: 'MDA',
        currencyCode: 'MDL',
        phoneCode: '+373',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 139,
        en: 'Montenegro',
        es: 'Montenegro',
        iso2: 'ME',
        iso3: 'MNE',
        currencyCode: 'EUR',
        phoneCode: '+382',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 140,
        en: 'Saint Martin',
        es: 'Isla de San Martín',
        iso2: 'MF',
        iso3: 'MAF',
        currencyCode: 'N/A',
        phoneCode: '+590',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 141,
        en: 'Madagascar',
        es: 'Madagascar',
        iso2: 'MG',
        iso3: 'MDG',
        currencyCode: 'MGA',
        phoneCode: '+261',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 142,
        en: 'Marshall Islands',
        es: 'Islas Marshall',
        iso2: 'MH',
        iso3: 'MHL',
        currencyCode: 'USD',
        phoneCode: '+692',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 143,
        en: 'The Former Yugoslav Republic of Macedonia',
        es: 'República de Macedonia del Norte',
        iso2: 'MK',
        iso3: 'MKD',
        currencyCode: 'MKD',
        phoneCode: '+389',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 144,
        en: 'Mali',
        es: 'Malí',
        iso2: 'ML',
        iso3: 'MLI',
        currencyCode: 'XOF',
        phoneCode: '+223',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 145,
        en: 'Myanmar',
        es: 'Myanmar',
        iso2: 'MM',
        iso3: 'MMR',
        currencyCode: 'MMK',
        phoneCode: '+95',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 146,
        en: 'Mongolia',
        es: 'Mongolia',
        iso2: 'MN',
        iso3: 'MNG',
        currencyCode: 'MNT',
        phoneCode: '+976',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 147,
        en: 'Macao',
        es: 'Macao',
        iso2: 'MO',
        iso3: 'MAC',
        currencyCode: 'N/A',
        phoneCode: '+853',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 148,
        en: 'Northern Mariana Islands',
        es: 'Islas Marianas del Norte',
        iso2: 'MP',
        iso3: 'MNP',
        currencyCode: 'N/A',
        phoneCode: '+1-670',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 149,
        en: 'Martinique',
        es: 'Martinica',
        iso2: 'MQ',
        iso3: 'MTQ',
        currencyCode: 'N/A',
        phoneCode: '+596',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 150,
        en: 'Mauritania',
        es: 'Mauritania',
        iso2: 'MR',
        iso3: 'MRT',
        currencyCode: 'MRU',
        phoneCode: '+222',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 151,
        en: 'Montserrat',
        es: 'Montserrat',
        iso2: 'MS',
        iso3: 'MSR',
        currencyCode: 'N/A',
        phoneCode: '+1-664',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 152,
        en: 'Malta',
        es: 'Malta',
        iso2: 'MT',
        iso3: 'MLT',
        currencyCode: 'EUR',
        phoneCode: '+356',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 153,
        en: 'Mauritius',
        es: 'Mauricio',
        iso2: 'MU',
        iso3: 'MUS',
        currencyCode: 'MUR',
        phoneCode: '+230',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 154,
        en: 'Maldives',
        es: 'Maldivas',
        iso2: 'MV',
        iso3: 'MDV',
        currencyCode: 'MVR',
        phoneCode: '+960',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 155,
        en: 'Malawi',
        es: 'Malawi',
        iso2: 'MW',
        iso3: 'MWI',
        currencyCode: 'MWK',
        phoneCode: '+265',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 156,
        en: 'Mexico',
        es: 'México',
        iso2: 'MX',
        iso3: 'MEX',
        currencyCode: 'MXN',
        phoneCode: '+52',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 157,
        en: 'Malaysia',
        es: 'Malasia',
        iso2: 'MY',
        iso3: 'MYS',
        currencyCode: 'MYR',
        phoneCode: '+60',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 158,
        en: 'Mozambique',
        es: 'Mozambique',
        iso2: 'MZ',
        iso3: 'MOZ',
        currencyCode: 'MZM',
        phoneCode: '+258',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 159,
        en: 'Namibia',
        es: 'Namibia',
        iso2: 'NA',
        iso3: 'NAM',
        currencyCode: 'NAD',
        phoneCode: '+264',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 160,
        en: 'New Caledonia',
        es: 'Nueva Caledonia',
        iso2: 'NC',
        iso3: 'NCL',
        currencyCode: 'N/A',
        phoneCode: '+687',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 161,
        en: 'Niger',
        es: 'Níger',
        iso2: 'NE',
        iso3: 'NER',
        currencyCode: 'XOF',
        phoneCode: '+227',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 162,
        en: 'Norfolk Island',
        es: 'Isla Norfolk',
        iso2: 'NF',
        iso3: 'NFK',
        currencyCode: 'N/A',
        phoneCode: '+672',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 163,
        en: 'Nigeria',
        es: 'Nigeria',
        iso2: 'NG',
        iso3: 'NGA',
        currencyCode: 'NGN',
        phoneCode: '+234',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 164,
        en: 'Nicaragua',
        es: 'Nicaragua',
        iso2: 'NI',
        iso3: 'NIC',
        currencyCode: 'NIO',
        phoneCode: '+505',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 165,
        en: 'Netherlands',
        es: 'Países Bajos',
        iso2: 'NL',
        iso3: 'NLD',
        currencyCode: 'EUR',
        phoneCode: '+31',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 166,
        en: 'Norway',
        es: 'Noruega',
        iso2: 'NO',
        iso3: 'NOR',
        currencyCode: 'NOK',
        phoneCode: '+47',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 167,
        en: 'Nepal',
        es: 'Nepal',
        iso2: 'NP',
        iso3: 'NPL',
        currencyCode: 'NPR',
        phoneCode: '+977',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 168,
        en: 'Nauru',
        es: 'Nauru',
        iso2: 'NR',
        iso3: 'NRU',
        currencyCode: 'AUD',
        phoneCode: '+674',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 169,
        en: 'Niue',
        es: 'Niue',
        iso2: 'NU',
        iso3: 'NIU',
        currencyCode: 'NZD',
        phoneCode: '+683',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 170,
        en: 'New Zealand',
        es: 'Nueva Zelandia',
        iso2: 'NZ',
        iso3: 'NZL',
        currencyCode: 'NZD',
        phoneCode: '+64',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 171,
        en: 'Oman',
        es: 'Omán',
        iso2: 'OM',
        iso3: 'OMN',
        currencyCode: 'OMR',
        phoneCode: '+968',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 172,
        en: 'Panama',
        es: 'Panamá',
        iso2: 'PA',
        iso3: 'PAN',
        currencyCode: 'PAB',
        phoneCode: '+507',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 173,
        en: 'Peru',
        es: 'Perú',
        iso2: 'PE',
        iso3: 'PER',
        currencyCode: 'PEN',
        phoneCode: '+51',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 174,
        en: 'French Polynesia',
        es: 'Polinesia Francesa',
        iso2: 'PF',
        iso3: 'PYF',
        currencyCode: 'N/A',
        phoneCode: '+689',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 175,
        en: 'Papua New Guinea',
        es: 'Papua Nueva Guinea',
        iso2: 'PG',
        iso3: 'PNG',
        currencyCode: 'PGK',
        phoneCode: '+675',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 176,
        en: 'Philippines',
        es: 'Filipinas',
        iso2: 'PH',
        iso3: 'PHL',
        currencyCode: 'PHP',
        phoneCode: '+63',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 177,
        en: 'Pakistan',
        es: 'Pakistán',
        iso2: 'PK',
        iso3: 'PAK',
        currencyCode: 'PKR',
        phoneCode: '+92',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 178,
        en: 'Poland',
        es: 'Polonia',
        iso2: 'PL',
        iso3: 'POL',
        currencyCode: 'PLN',
        phoneCode: '+48',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 179,
        en: 'Saint Pierre and Miquelon',
        es: 'San Pedro y Miquelón',
        iso2: 'PM',
        iso3: 'SPM',
        currencyCode: 'N/A',
        phoneCode: '+508',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 180,
        en: 'Pitcairn',
        es: 'Islas Pitcairn',
        iso2: 'PN',
        iso3: 'PCN',
        currencyCode: 'N/A',
        phoneCode: '+870',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 181,
        en: 'Puerto Rico',
        es: 'Puerto Rico',
        iso2: 'PR',
        iso3: 'PRI',
        currencyCode: 'N/A',
        phoneCode: '+1',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 182,
        en: 'State of Palestine',
        es: 'Estado de Palestina',
        iso2: 'PS',
        iso3: 'PSE',
        currencyCode: 'N/A',
        phoneCode: '+970',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 183,
        en: 'Portugal',
        es: 'Portugal',
        iso2: 'PT',
        iso3: 'PRT',
        currencyCode: 'EUR',
        phoneCode: '+351',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 184,
        en: 'Palau',
        es: 'Palau',
        iso2: 'PW',
        iso3: 'PLW',
        currencyCode: 'USD',
        phoneCode: '+680',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 185,
        en: 'Paraguay',
        es: 'Paraguay',
        iso2: 'PY',
        iso3: 'PRY',
        currencyCode: 'PYG',
        phoneCode: '+595',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 186,
        en: 'Qatar',
        es: 'Qatar',
        iso2: 'QA',
        iso3: 'QAT',
        currencyCode: 'QAR',
        phoneCode: '+974',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 187,
        en: 'Reunion',
        es: 'Reunión',
        iso2: 'RE',
        iso3: 'REU',
        currencyCode: 'N/A',
        phoneCode: '+262',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 188,
        en: 'Romania',
        es: 'Rumania',
        iso2: 'RO',
        iso3: 'ROU',
        currencyCode: 'RON',
        phoneCode: '+40',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 189,
        en: 'Serbia',
        es: 'Serbia',
        iso2: 'RS',
        iso3: 'SRB',
        currencyCode: 'RSD',
        phoneCode: '+381',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 190,
        en: 'Russian Federation',
        es: 'Federación de Rusia',
        iso2: 'RU',
        iso3: 'RUS',
        currencyCode: 'RUB',
        phoneCode: '+7',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 191,
        en: 'Rwanda',
        es: 'Rwanda',
        iso2: 'RW',
        iso3: 'RWA',
        currencyCode: 'RWF',
        phoneCode: '+250',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 192,
        en: 'Saudi Arabia',
        es: 'Arabia Saudita',
        iso2: 'SA',
        iso3: 'SAU',
        currencyCode: 'SAR',
        phoneCode: '+966',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 193,
        en: 'Solomon Islands',
        es: 'Islas Salomón',
        iso2: 'SB',
        iso3: 'SLB',
        currencyCode: 'SBD',
        phoneCode: '+677',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 194,
        en: 'Seychelles',
        es: 'Seychelles',
        iso2: 'SC',
        iso3: 'SYC',
        currencyCode: 'SCR',
        phoneCode: '+248',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 195,
        en: 'Sudan',
        es: 'Sudán',
        iso2: 'SD',
        iso3: 'SDN',
        currencyCode: 'SDG',
        phoneCode: '+249',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 196,
        en: 'Sweden',
        es: 'Suecia',
        iso2: 'SE',
        iso3: 'SWE',
        currencyCode: 'SEK',
        phoneCode: '+46',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 197,
        en: 'Singapore',
        es: 'Singapur',
        iso2: 'SG',
        iso3: 'SGP',
        currencyCode: 'SGD',
        phoneCode: '+65',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 198,
        en: 'Saint Helena',
        es: 'Santa Elena',
        iso2: 'SH',
        iso3: 'SHN',
        currencyCode: 'N/A',
        phoneCode: '+290',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 199,
        en: 'Slovenia',
        es: 'Eslovenia',
        iso2: 'SI',
        iso3: 'SVN',
        currencyCode: 'EUR',
        phoneCode: '+386',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 200,
        en: 'Svalbard and Jan Mayen',
        es: 'Svalbard y Jan Mayen',
        iso2: 'SJ',
        iso3: 'SJM',
        currencyCode: 'N/A',
        phoneCode: '+47',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 201,
        en: 'Slovakia',
        es: 'Eslovaquia',
        iso2: 'SK',
        iso3: 'SVK',
        currencyCode: 'EUR',
        phoneCode: '+421',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 202,
        en: 'Sierra Leone',
        es: 'Sierra Leona',
        iso2: 'SL',
        iso3: 'SLE',
        currencyCode: 'SLL',
        phoneCode: '+232',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 203,
        en: 'San Marino',
        es: 'San Marino',
        iso2: 'SM',
        iso3: 'SMR',
        currencyCode: 'EUR',
        phoneCode: '+378',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 204,
        en: 'Senegal',
        es: 'Senegal',
        iso2: 'SN',
        iso3: 'SEN',
        currencyCode: 'XOF',
        phoneCode: '+221',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 205,
        en: 'Somalia',
        es: 'Somalia',
        iso2: 'SO',
        iso3: 'SOM',
        currencyCode: 'SOS',
        phoneCode: '+252',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 206,
        en: 'Suriname',
        es: 'Suriname',
        iso2: 'SR',
        iso3: 'SUR',
        currencyCode: 'SRD',
        phoneCode: '+597',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 207,
        en: 'South Sudan',
        es: 'Sudán del Sur',
        iso2: 'SS',
        iso3: 'SSD',
        currencyCode: 'SSP',
        phoneCode: '+211',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 208,
        en: 'Sao Tome and Principe',
        es: 'Santo Tomé y Príncipe',
        iso2: 'ST',
        iso3: 'STP',
        currencyCode: 'STN',
        phoneCode: '+239',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 209,
        en: 'El Salvador',
        es: 'El Salvador',
        iso2: 'SV',
        iso3: 'SLV',
        currencyCode: 'USD',
        phoneCode: '+503',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 210,
        en: 'Sint Maarten',
        es: 'Sint Maarten',
        iso2: 'SX',
        iso3: 'SXM',
        currencyCode: 'N/A',
        phoneCode: '+1-721',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 211,
        en: 'Syrian Arab Republic',
        es: 'República Árabe Siria',
        iso2: 'SY',
        iso3: 'SYR',
        currencyCode: 'SYP',
        phoneCode: '+963',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 212,
        en: 'Swaziland',
        es: 'Eswatini',
        iso2: 'SZ',
        iso3: 'SWZ',
        currencyCode: 'SZL',
        phoneCode: '+268',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 213,
        en: 'Turks and Caicos Islands',
        es: 'Islas Turcas y Caicos',
        iso2: 'TC',
        iso3: 'TCA',
        currencyCode: 'N/A',
        phoneCode: '+1-649',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 214,
        en: 'Chad',
        es: 'Chad',
        iso2: 'TD',
        iso3: 'TCD',
        currencyCode: 'XAF',
        phoneCode: '+235',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 215,
        en: 'French Southern Territories',
        es: 'Territorios Australes Franceses',
        iso2: 'TF',
        iso3: 'ATF',
        currencyCode: 'N/A',
        phoneCode: '+262',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 216,
        en: 'Togo',
        es: 'Togo',
        iso2: 'TG',
        iso3: 'TGO',
        currencyCode: 'XOF',
        phoneCode: '+228',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 217,
        en: 'Thailand',
        es: 'Tailandia',
        iso2: 'TH',
        iso3: 'THA',
        currencyCode: 'THB',
        phoneCode: '+66',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 218,
        en: 'Tajikistan',
        es: 'Tayikistán',
        iso2: 'TJ',
        iso3: 'TJK',
        currencyCode: 'TJS',
        phoneCode: '+992',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 219,
        en: 'Tokelau',
        es: 'Tokelau',
        iso2: 'TK',
        iso3: 'TKL',
        currencyCode: 'N/A',
        phoneCode: '+690',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 220,
        en: 'Timor-Leste',
        es: 'Timor-Leste',
        iso2: 'TL',
        iso3: 'TLS',
        currencyCode: 'USD',
        phoneCode: '+670',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 221,
        en: 'Turkmenistan',
        es: 'Turkmenistán',
        iso2: 'TM',
        iso3: 'TKM',
        currencyCode: 'TMT',
        phoneCode: '+993',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 222,
        en: 'Tunisia',
        es: 'Túnez',
        iso2: 'TN',
        iso3: 'TUN',
        currencyCode: 'TND',
        phoneCode: '+216',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 223,
        en: 'Tonga',
        es: 'Tonga',
        iso2: 'TO',
        iso3: 'TON',
        currencyCode: 'TOP',
        phoneCode: '+676',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 224,
        en: 'Turkey',
        es: 'Turquía',
        iso2: 'TR',
        iso3: 'TUR',
        currencyCode: 'TRY',
        phoneCode: '+90',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 225,
        en: 'Trinidad and Tobago',
        es: 'Trinidad y Tabago',
        iso2: 'TT',
        iso3: 'TTO',
        currencyCode: 'TTD',
        phoneCode: '+1-868',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 226,
        en: 'Tuvalu',
        es: 'Tuvalu',
        iso2: 'TV',
        iso3: 'TUV',
        currencyCode: 'AUD',
        phoneCode: '+688',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 227,
        en: 'Taiwan',
        es: 'Taiwan',
        iso2: 'TW',
        iso3: 'TWN',
        currencyCode: 'N/A',
        phoneCode: '+886',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 228,
        en: 'United Republic of Tanzania',
        es: 'República Unida de Tanzanía',
        iso2: 'TZ',
        iso3: 'TZA',
        currencyCode: 'TZS',
        phoneCode: '+255',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 229,
        en: 'Ukraine',
        es: 'Ucrania',
        iso2: 'UA',
        iso3: 'UKR',
        currencyCode: 'UAH',
        phoneCode: '+380',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 230,
        en: 'Uganda',
        es: 'Uganda',
        iso2: 'UG',
        iso3: 'UGA',
        currencyCode: 'UGS',
        phoneCode: '+256',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 231,
        en: 'United States of America',
        es: 'Estados Unidos de América',
        iso2: 'US',
        iso3: 'USA',
        currencyCode: 'USD',
        phoneCode: '+1',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 232,
        en: 'Uruguay',
        es: 'Uruguay',
        iso2: 'UY',
        iso3: 'URY',
        currencyCode: 'UYU',
        phoneCode: '+598',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 233,
        en: 'Uzbekistan',
        es: 'Uzbekistán',
        iso2: 'UZ',
        iso3: 'UZB',
        currencyCode: 'UZS',
        phoneCode: '+998',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 234,
        en: 'Holy See',
        es: 'Santa Sede',
        iso2: 'VA',
        iso3: 'VAT',
        currencyCode: 'N/A',
        phoneCode: '+379',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 235,
        en: 'Saint Vincent and the Grenadines',
        es: 'San Vicente y las Granadinas',
        iso2: 'VC',
        iso3: 'VCT',
        currencyCode: 'XCD',
        phoneCode: '+1-784',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 236,
        en: 'Venezuela',
        es: 'Venezuela',
        iso2: 'VE',
        iso3: 'VEN',
        currencyCode: 'VEF',
        phoneCode: '+58',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 237,
        en: 'British Virgin Islands',
        es: 'Islas Vírgenes Británicas',
        iso2: 'VG',
        iso3: 'VGB',
        currencyCode: 'N/A',
        phoneCode: '+1-284',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 238,
        en: 'US Virgin Islands',
        es: 'Islas Vírgenes de los Estados Unidos',
        iso2: 'VI',
        iso3: 'VIR',
        currencyCode: 'N/A',
        phoneCode: '+1-340',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 239,
        en: 'Vietnam',
        es: 'Viet Nam',
        iso2: 'VN',
        iso3: 'VNM',
        currencyCode: 'VND',
        phoneCode: '+84',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 240,
        en: 'Vanuatu',
        es: 'Vanuatu',
        iso2: 'VU',
        iso3: 'VUT',
        currencyCode: 'VUV',
        phoneCode: '+678',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 241,
        en: 'Wallis and Futuna',
        es: 'Wallis y Futuna',
        iso2: 'WF',
        iso3: 'WLF',
        currencyCode: 'N/A',
        phoneCode: '+681',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 242,
        en: 'Samoa',
        es: 'Samoa',
        iso2: 'WS',
        iso3: 'WSM',
        currencyCode: 'WST',
        phoneCode: '+685',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 243,
        en: 'Kosovo',
        es: 'Kosovo',
        iso2: 'XK',
        iso3: 'XKX',
        currencyCode: 'EUR',
        phoneCode: '+383',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 244,
        en: 'Yemen',
        es: 'Yemen',
        iso2: 'YE',
        iso3: 'YEM',
        currencyCode: 'YER',
        phoneCode: '+967',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 245,
        en: 'Mayotte',
        es: 'Mayotte',
        iso2: 'YT',
        iso3: 'MYT',
        currencyCode: 'N/A',
        phoneCode: '+262',
        isActive: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 246,
        en: 'South Africa',
        es: 'Sudáfrica',
        iso2: 'ZA',
        iso3: 'ZAF',
        currencyCode: 'ZAR',
        phoneCode: '+27',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 247,
        en: 'Zambia',
        es: 'Zambia',
        iso2: 'ZM',
        iso3: 'ZMB',
        currencyCode: 'ZMK',
        phoneCode: '+260',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 248,
        en: 'Zimbabwe',
        es: 'Zimbabwe',
        iso2: 'ZW',
        iso3: 'ZWE',
        currencyCode: 'ZWD',
        phoneCode: '+263',
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]);
  },

  async down (queryInterface: QueryInterface, Sequelize: any) {
    return await queryInterface.bulkDelete('country_cat', { id: { [Op.gt]: 0 } });
  }
};
